spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://devx.cmarky7auuui.eu-north-1.rds.amazonaws.com:5432/devx
    username: acheron
    password: qwerty123222
