spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://devx.cmarky7auuui.eu-north-1.rds.amazonaws.com:5432/devx
    username: acheron
    password: qwerty123222

aws:
  region: eu-north-1
  access_key: AKIA5Q2A6DOFL2PUM7NX
  secret_access_key: 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
  bucket_name: devx-int20h
  path_to_images: /auction